WINDOW_TITLE = "Evolution Simulation"

GRID_SIZE_X = 100
GRID_SIZE_Y = 100
BLOCK_SIZE = 10

POPULATION = 10
NUMBER_OF_SYNAPSES = 8
INTERNAL_NEURONS = 1

MUTATION_RATE = 0.005
VISION_RANGE = 3

MAX_FPS = 100

PAUSE_ON_NEW_GENERATION = False
NUMBER_OF_GENERATIONS = 1000
STEPS_PER_GENERATION = 300
GENERATION_STEP_COUNT = 0
GENERATION_COUNT = 0

